---
title: "Derivatives in R Practice"
author: "Erica Dale"
date: "2022-08-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(palmerpenguins)
```
Edit through github.
Now edit through Rstudio.

## Solving derivatives

$f(x) = x2 at x = 3$

```{r}
first_problem <- expression(x^2)
first_deriv <- deriv(first_problem, "x")
x <- 3
eval(first_deriv)

```

$P(a) = 2 * (3a + 2) ^ 4 - 5  at a = 1.2$

```{r}
second_p <- expression(2 * (3*a + 4)^4 - 5)
second_d <- D(second_p, "a")
a <- 1.2
eval(second_d)
```

$g(t) = (-4t) / (t^2 + 1)^3 at t=0$

```{r}
third_p <- expression((-4 * t) / ((t^2 + 1)^3))
third_d <- deriv(third_p, "t")
t <- 0
eval(third_d)
```


## Adding a plot

```{r}
ggplot(data = penguins, 
       aes(x = bill_length_mm, y = bill_depth_mm)) +
  geom_point(aes(color = species)) +
  labs(title = "Comparing Bill Shapes", x = "Bill Length (mm)", y = "Bill Depth (mm)")
```


Jitterplot of flipper length by species
```{r}
ggplot(data = penguins,
       aes(x = species, y = flipper_length_mm, size = species, color = sex)) +
  geom_jitter() +
  labs(title = "Flipper length by species", x = "Species", y = "Flipper Length (mm)") +
  ggtitle(label = "Where is this", subtitle = "Does this work")
```

